Caascad/toolbox

- default.nix
- nix/sources.json
- pkgs/tf.nix
> Add tf resource

- .github/workflows/test.yml
- install
- pkgs/toolbox/default.nix
- pkgs/toolbox/toolbox.sh
> toolbox: 1.6 -> 1.7

- pkgs/pre-commit-terraform.nix
> pre-commit-terraform: no patch in the installed GIT hooks

- pkgs/kswitch/default.nix
- pkgs/kswitch/kswitch.sh
> kswitch: 1.3.2 -> 1.4.0

- pkgs/kswitch/default.nix
- pkgs/kswitch/kswitch.sh
> kswitch: 1.4.0 -> 1.4.1

- pkgs/kswitch/default.nix
- pkgs/kswitch/kswitch.sh
Improve argument parsing, add --version option
> kswitch: 1.4.1 -> 1.4.2

- default.nix
- nix/sources.json
- pkgs/helm-plugins/default.nix
- pkgs/helm-with-plugins.nix
> helm-with-plugins: init

- default.nix
- nix/sources.json
- pkgs/terraform-provider-azurerm.nix
Adding azurem terraform provider
> terraform-provider-azurerm: init at 2.51.0

- default.nix
- pkgs/ansible-plugins/default.nix
- pkgs/ansible-plugins/stats_exporter.py
- pkgs/ansible-with-plugins.nix
Added stats_exporter callback plugin
> ansible-with-plugins: init

- pkgs/kswitch/default.nix
- pkgs/kswitch/kswitch.sh
Add cache to prevent Throttling
> kswitch: 1.7.0 -> 1.8.0

- pkgs/kswitch/default.nix
- pkgs/kswitch/kswitch.sh
Add trap to clean remaining locks
> kswitch: further prevent orphan locks

- autoupdate/config.yml
- nix/sources.json
- pkgs/cue.nix
- pkgs/fly.nix
- pkgs/velero.nix
- toolbox.json
terraform-provider-aws : 3.57.0 -> 3.58.0
terraform-provider-azuread : 2.1.0 -> 2.2.0
terraform-provider-azurerm : 2.75.0 -> 2.76.0
> remove deprecated buildFlagsArray

- nix/sources.json
- pkgs/kswitch/default.nix
- pkgs/kswitch/kswitch.sh
> Update terraform-provider-kubernetes-yaml provider

- .github/workflows/test.yml
- default.nix
- pkgs/toolbox/toolbox.sh
It's been removed from nixpkgs.
> terraform_0_12: remove

- pkgs/kubectl-with-plugins.nix
We reuse the installPhase of nixpkgs kubectl which does this.
> kubectl-with-plugins: install completions

- pkgs/os/default.nix
- pkgs/os/os.sh
Use infra-zone domain name for ngot zone
> os: fix domain name for vault on ngot zones

- pkgs/amtool-caascad/amtool-caascad.sh
- pkgs/amtool-caascad/default.nix
Fix hardcoded domain_name in caascad-amtool
> amtool-caascad: fix hardcoded domain_name

- pkgs/amtool-caascad/amtool-caascad.sh
- pkgs/amtool-caascad/default.nix
- pkgs/kswitch/default.nix
- pkgs/kswitch/kswitch.sh
Fix a bug with uninitialized var.
> caascad-amtool: fix uninitialized var

- nix/sources.json
> Update privx terraform provider

- nix/sources.json
Last tag of loki has broken the autoupdate feature. Disabling loki autoupdate
> Disable loki autoupdate

- pkgs/print-client-zones-infos/default.nix
- pkgs/print-client-zones-infos/print-client-zones-infos.sh
- monitoring-stack-client: show if Prometheus exposes its API
- duplicated monitoring-stack as monitoring-stack-corp
- print cluster infos
> Print kub and other improvments
